"""Media generation seam (02-port-contracts §2 pattern; 06-domain-models §8
"RunMediaJob (worker)").

A module-local seam over the adapter that combines the framework
``ImageProvider``/``VideoProvider`` ports (02-port-contracts §1.3/§1.4) with
the ``files`` module's storage of the generated bytes — neither of which is
referenced here. This mirrors the ``knowledge.EmbeddingResolver`` seam
(``knowledge/ports/retrieval.py``): the inbound-facing use-case
(``RunMediaJob``) is fixed by contract and knows nothing about *how* a job is
generated, only that something implementing this narrow protocol can do it.

**The adapter exists, and the seam STAYS.** It was described here as
"temporary, standing in for the deferred Phase-5 adapter" until steps 19-20
of ``deferred-adapters-plan.md`` (``docs/log/3.103.md`` ·
``docs/log/3.104.md``) shipped ``WorkerMediaGenerator``
(``app/workers/media_generation.py``) and wired it in
``build_media_worker_from_env``. Two things follow, and the second is why
this file changed by only its prose:

* The promise above was KEPT literally — the generator was bound behind this
  same Protocol, and ``RunMediaJob`` was not touched.
* The seam is not now redundant. ``WorkerMediaGenerator`` joins ``media``'s
  vocabulary to the ``files`` module's upload lifecycle, which
  ``.importlinter``'s ``modules-independent`` contract forbids inside
  ``app.modules.*``; it therefore lives in ``app.workers``, which
  ``app.modules.media`` may not import. The Protocol is precisely what lets
  a use-case here be driven by an implementation there — the
  ``knowledge.DocumentContentResolver`` situation exactly (step 16), and the
  reason that seam stayed too.

Note the wiring site is the WORKER's composition root
(``workers/bootstrap.py``), not the API's ``CompositionRoot`` as this
docstring once predicted: generation runs in the ``media`` process, and the
API never constructs a ``MediaGenerator`` at all.
"""

from __future__ import annotations

from typing import Protocol

from app.framework.context.execution_context import ExecutionContext
from app.framework.types import Uuid
from app.modules.media.domain.value_objects import GenParams, MediaKind


class MediaGenerator(Protocol):
    """Runs one generation job end-to-end and returns the resulting
    ``files`` module file id (``result_file_id``).

    Implementations own calling the resolved provider (image/video),
    persisting the returned bytes through ``files``, and translating any
    failure into a raised exception — ``RunMediaJob`` catches ``Exception``
    broadly and records it as the job's ``error`` (06 §8; the
    ``knowledge.IndexDocument``/``IndexRegisteredDocument`` precedent).
    """

    async def generate(
        self, ctx: ExecutionContext, *, kind: MediaKind, prompt: str, params: GenParams
    ) -> Uuid: ...
