"""Media generation seam (02-port-contracts §2 pattern; 06-domain-models §8
"RunMediaJob (worker)").

A temporary, module-local seam standing in for the (deferred, Phase-5) infra
adapter that will combine the framework ``ImageProvider``/``VideoProvider``
ports (02-port-contracts §1.3/§1.4) with the ``files`` module's storage of the
generated bytes — neither of which is referenced here. This mirrors the
``knowledge.EmbeddingResolver`` seam (``knowledge/ports/retrieval.py``): the
inbound-facing use-case (``RunMediaJob``) is fixed by contract and knows
nothing about *how* a job is generated, only that something implementing this
narrow protocol can do it; once the Phase-5 adapter exists, the Composition
Root wires it in behind this same seam without touching ``RunMediaJob``.
"""

from __future__ import annotations

from typing import Protocol

from app.framework.context.execution_context import ExecutionContext
from app.framework.types import Uuid
from app.modules.media.domain.value_objects import GenParams, MediaKind


class MediaGenerator(Protocol):
    """Runs one generation job end-to-end and returns the resulting
    ``files`` module file id (``result_file_id``).

    Implementations own calling the resolved provider (image/video),
    persisting the returned bytes through ``files``, and translating any
    failure into a raised exception — ``RunMediaJob`` catches ``Exception``
    broadly and records it as the job's ``error`` (06 §8; the
    ``knowledge.IndexDocument``/``IndexRegisteredDocument`` precedent).
    """

    async def generate(
        self, ctx: ExecutionContext, *, kind: MediaKind, prompt: str, params: GenParams
    ) -> Uuid: ...
