"""No generated or machine-droppings file may be tracked in git, and the
ignore rules must cover the whole CLASS -- not the one path that slipped in
(release-blockers-plan.md §3, step 6 · pre-release-review.md P1).

Two files were tracked in the index when this guard was written:

* ``.coverage`` -- the local SQLite database ``pytest --cov`` rewrites on every
  run. Committed, it produces a binary diff per test run and merge conflicts
  nobody can resolve.
* ``docs/ROADMAP.md:Zone.Identifier`` -- a 25-byte NTFS *alternate data stream*
  stub. Downloading any file with a Windows browser leaves one next to it;
  from WSL it looks like an ordinary file with a colon in its name, and
  ``git add .`` picks it up silently.

``.gitignore`` carried **no** rule for either, so both would come straight back
on the next ``pytest --cov`` / next downloaded document.

The lesson this module applies is the one the step-3 review paid for: two
things drifted and nothing compared them. So the fix is not "remove those two
paths" but "state the classes, and check both directions":

1. no tracked path matches a known junk class (the defect itself), and
2. ``.gitignore`` actually *ignores* representative members of each class --
   asked of ``git`` itself via ``check-ignore``, not by grepping the file for
   a line that looks right. A rule can be present and still not match (leading
   slash, trailing slash on a non-directory, a stray ``**``).

And the mirror of 2: a pattern broad enough to swallow real content
(``.env.example``, a document) would be a worse regression than the junk it
removes, so that is asserted too.
"""

from __future__ import annotations

import subprocess
from pathlib import Path, PurePosixPath

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Names that are never source: each is regenerated by a tool or dropped by an
# operating system, and each has bitten this repository or is one keystroke
# away from doing so. Keep the reason with the rule -- a bare list of globs
# invites someone to delete an entry they cannot justify keeping.
_EXACT_NAMES: dict[str, str] = {
    ".coverage": "coverage.py's SQLite database, rewritten by every `pytest --cov` run",
    "coverage.xml": "coverage.py's XML report, regenerated on demand",
    ".DS_Store": "macOS Finder metadata",
    "Thumbs.db": "Windows Explorer thumbnail cache",
    "desktop.ini": "Windows Explorer folder settings",
    ".env": "the real environment file -- holds secrets; `.env.example` is the tracked template",
}
_NAME_PREFIXES: dict[str, str] = {
    ".coverage.": "a per-process coverage database (`coverage combine` input)",
}
_NAME_SUFFIXES: dict[str, str] = {
    ":Zone.Identifier": "an NTFS alternate data stream stub left by a Windows download",
    ".pyc": "compiled Python bytecode",
    ".pyo": "compiled Python bytecode",
    ".orig": "a merge-conflict leftover",
    ".rej": "a rejected-patch leftover",
    ".swp": "a Vim swap file",
}
_DIRECTORY_COMPONENTS: dict[str, str] = {
    "__pycache__": "a Python bytecode cache directory",
    "htmlcov": "coverage.py's generated HTML report directory",
    ".ruff_cache": "a Ruff cache directory",
    ".mypy_cache": "a mypy cache directory",
    ".pytest_cache": "a pytest cache directory",
}

# One representative of each class, deliberately NOT the paths that were
# actually tracked: the rule has to cover the next occurrence, not this one.
_MUST_BE_IGNORED: tuple[str, ...] = (
    ".coverage",
    ".coverage.somehost.4711",
    "coverage.xml",
    "htmlcov/index.html",
    "docs/quickstart.md:Zone.Identifier",
    "src/app/api/main.py:Zone.Identifier",
    "Thumbs.db",
    "desktop.ini",
    ".DS_Store",
)
# The mirror: over-broad ignore rules silently drop real files from `git add`,
# which is how content disappears without anyone noticing.
_MUST_NOT_BE_IGNORED: tuple[str, ...] = (
    ".env.example",
    "docs/ROADMAP.md",
    "docs/log/INDEX.md",
    "pyproject.toml",
    "src/app/api/main.py",
    "tests/unit/test_repo_hygiene.py",
)


def junk_reason(path: str) -> str | None:
    """Why ``path`` must never be tracked, or ``None`` if it is legitimate.

    Pure: takes a POSIX-style repository-relative path, touches no filesystem.
    That is what lets the classes be asserted directly, including on the two
    paths that were genuinely in the index before step 6.
    """
    parts = PurePosixPath(path).parts
    for component, reason in _DIRECTORY_COMPONENTS.items():
        if component in parts:
            return reason
    name = parts[-1] if parts else path
    exact = _EXACT_NAMES.get(name)
    if exact is not None:
        return exact
    for prefix, reason in _NAME_PREFIXES.items():
        if name.startswith(prefix):
            return reason
    for suffix, reason in _NAME_SUFFIXES.items():
        if name.endswith(suffix):
            return reason
    if name.endswith("~"):
        return "an editor backup file"
    return None


def _git(*args: str) -> str:
    """Run git in the repository, skipping honestly when git cannot answer.

    A guard that quietly evaluates an empty file list would pass forever while
    guarding nothing (the 3.69 lesson). Skipping says so out loud instead.
    """
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=_REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover - no git binary
        pytest.skip(f"git is not runnable here, so tracked-file hygiene cannot be checked: {exc}")
    if completed.returncode != 0:  # pragma: no cover - not a git work tree
        pytest.skip(
            f"`git {' '.join(args)}` failed (rc={completed.returncode}); "
            "this is not a git work tree, so tracked-file hygiene cannot be checked."
        )
    return completed.stdout


def _tracked_paths() -> list[str]:
    out = _git("ls-files", "-z")
    return [entry for entry in out.split("\0") if entry]


def _is_ignored(path: str) -> bool:
    """Ask git, not the text of `.gitignore`.

    ``--no-index`` is what makes this answer the question that matters: would
    a *new* file at this path be ignored -- independent of whether one exists
    on disk or is already tracked.
    """
    try:
        completed = subprocess.run(
            ["git", "check-ignore", "--no-index", "-q", "--", path],
            cwd=_REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover - no git binary
        pytest.skip(f"git is not runnable here, so ignore rules cannot be checked: {exc}")
    if completed.returncode not in (0, 1):  # pragma: no cover - not a git work tree
        pytest.skip(
            f"`git check-ignore` failed for {path!r} (rc={completed.returncode}); "
            "this is not a git work tree, so ignore rules cannot be checked."
        )
    return completed.returncode == 0


def test_the_matcher_recognises_the_files_that_were_actually_tracked() -> None:
    """Anchor the classifier to the real defect before trusting it.

    Both of these were in `git ls-files` until step 6. A matcher that stopped
    recognising them would leave the guard below green and empty.
    """
    assert junk_reason(".coverage") is not None
    assert junk_reason("docs/ROADMAP.md:Zone.Identifier") is not None
    # ...and the mirror: it must not flag ordinary repository content.
    for legitimate in _MUST_NOT_BE_IGNORED:
        assert junk_reason(legitimate) is None, (
            f"{legitimate} is real repository content but the junk matcher flagged it"
        )


def test_no_tracked_file_is_generated_or_machine_droppings() -> None:
    """The defect itself: `git ls-files` must contain no member of any class."""
    offenders = {path: reason for path in _tracked_paths() if (reason := junk_reason(path))}
    assert not offenders, "tracked files that must never be committed:\n" + "\n".join(
        f"  {path} -- {reason}" for path, reason in sorted(offenders.items())
    )


def test_the_tracked_file_list_is_not_empty() -> None:
    """`git ls-files` returning nothing would make the check above vacuous."""
    tracked = _tracked_paths()
    assert len(tracked) > 100, (
        f"only {len(tracked)} tracked files found -- the hygiene check above "
        "would be vacuously true; is this really the repository root?"
    )


@pytest.mark.parametrize("path", _MUST_BE_IGNORED)
def test_gitignore_covers_the_class_not_just_the_path_that_slipped_in(path: str) -> None:
    """Removing a file from the index without an ignore rule buys one commit
    of cleanliness: the next `pytest --cov`, the next downloaded document,
    brings it straight back. Note none of these are the two paths that were
    actually tracked -- the rule has to cover the class."""
    assert _is_ignored(path), (
        f"{path} is not ignored -- `git check-ignore --no-index {path}` finds no "
        "rule, so it will be re-added by the next `git add .`"
    )


@pytest.mark.parametrize("path", _MUST_NOT_BE_IGNORED)
def test_gitignore_does_not_swallow_real_content(path: str) -> None:
    """The failure mode worse than the one being fixed: an over-broad rule
    (`*.env`, `*coverage*`, a bare `*:*`) drops real files out of `git add`
    silently, and nothing reports a file that was never staged."""
    assert not _is_ignored(path), (
        f"{path} is real repository content but `.gitignore` ignores it -- "
        "an ignore rule added for generated files is too broad"
    )
