#!/usr/bin/env bash
# Prove the HARNESS, not the platform -- in about half a minute.
#
#   deploy/load/smoke.sh
#
# Why this exists. `deploy/load/` was written in full -- five scenarios, two
# profiles, a threshold sheet, a token pool and a summary writer -- before
# anything could execute a line of it, because k6 was not installed anywhere
# (capacity blocker د‑3). The first execution found THREE bugs that no amount
# of reading had:
#
#   * `k6/net/websockets` does not exist. Two scenarios imported it; every k6
#     in the 1.x line answers `unknown module` and aborts at init.
#   * `constant-arrival-rate` refuses a fractional `rate`. §0's own arithmetic
#     is fractional (100 index jobs a MINUTE is 1.67/s), so BOTH profiles were
#     unrunnable, with an error naming neither the scenario nor the field.
#   * `open('./tokens.json')` resolves against the MODULE, not the working
#     directory, so the default pool path pointed at `lib/tokens.json`.
#
# None of the three is reachable by review, all three are caught by one short
# run, and the next edit to this harness deserves the same check. So: a stub
# pool, twenty seconds, the full peak scenario mix.
#
# ⚠️ THIS IS NOT A MEASUREMENT AND CANNOT BECOME ONE. The pool is synthetic,
# so every request is a 401 and the error-rate threshold fails BY DESIGN --
# the exit code is expected to be k6's 99. What is being asserted is that the
# scripts parse, the scenarios execute at their stated rates, the metrics are
# collected and the archive is written with `valid: false` in it. The result
# is written under `results/smoke-*` so it can never be mistaken for a run.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

duration="${LOAD_DURATION_S:-20}"
pool="deploy/load/results/smoke-tokens.json"
mkdir -p deploy/load/results

# Four tokens, and `LOAD_WS_VUS=6` below stays inside `profile.js`'s "no more
# than 3 sockets per user" guard -- the same guard a real 1,500-socket run has
# to satisfy with 500 tokens.
python3 - "$pool" <<'PY'
import base64, json, sys, time

def seg(obj):
    return base64.urlsafe_b64encode(json.dumps(obj).encode()).decode().rstrip("=")

# A structurally valid, deliberately unsigned JWT: `auth.js` reads only the
# `exp` claim (to refuse a pool that expires mid-run), and the platform will
# reject the signature -- which is the point.
header = seg({"alg": "RS256", "kid": ""})
tokens = [
    {
        "workspace": f"smoke-{i:04d}",
        "space_id": f"00000000-0000-0000-0000-00000000000{i}",
        "id_token": f"{header}.{seg({'sub': f'smoke-{i:04d}', 'exp': int(time.time()) + 3600})}.NOTASIGNATURE",
    }
    for i in range(1, 5)
]
json.dump(
    {
        "_comment": "Generated by deploy/load/smoke.sh. Synthetic. Never a baseline.",
        "stub": True,
        "minted_at": "1970-01-01T00:00:00Z",
        "tokens": tokens,
    },
    open(sys.argv[1], "w"),
    indent=2,
)
PY

echo "smoke: $duration s of the peak mix against a synthetic pool — 401s and a failed"
echo "       error-rate threshold are the EXPECTED outcome."
echo

# ABSOLUTE, and not for tidiness: k6's `open()` resolves a relative path
# against the MODULE that calls it (`lib/auth.js`), not the working directory,
# so a relative pool path works in the container -- where `run.sh` rewrites it
# -- and silently misses on a host k6.
set +e
LOAD_TOKEN_FILE="$repo_root/$pool" \
  LOAD_DURATION_S="$duration" \
  LOAD_WS_VUS=6 \
  LOAD_OUT="deploy/load/results/smoke-$(date -u +%Y%m%dT%H%M%SZ).json" \
  deploy/load/run.sh peak
status=$?
set -e

rm -f "$pool"

# 99 is k6's "a threshold was crossed", which is what a synthetic pool must
# produce. 0 would mean the error-rate threshold PASSED on 401s -- a broken
# threshold, not a healthy harness. Anything else is the harness failing to
# start, which is what this script is for.
case "$status" in
  99)
    echo
    echo "smoke: OK — scripts parsed, scenarios ran, thresholds evaluated, archive written."
    exit 0
    ;;
  0)
    echo "smoke: FAILED — every request 401'd and the error-rate threshold still passed." >&2
    exit 1
    ;;
  *)
    echo "smoke: FAILED — the harness did not complete a run (exit $status)." >&2
    exit "$status"
    ;;
esac
